name: apotek_bloc
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  bloc: ^7.2.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^7.3.1
  flutter_svg: ^0.23.0+1
  get: ^4.3.8
  meta: ^1.7.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  bloc_test: 8.3.0
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
     - assets\icons
     - assets\images

